-- AlterTable
ALTER TABLE `TaskEvent` ADD COLUMN `userId` VARCHAR(191) NOT NULL,
    MODIFY `eventType` ENUM('CREATED', 'STARTED', 'COMPLETED', 'UNCOMPLETED', 'ARCHIVED', 'UNARCHIVED', 'DELETED', 'RESTORED', 'ESTIMATE_CHANGED', 'SUBTASK_CREATED', 'SUBTASK_REMOVED', 'TAGS_CHANGED', 'TODO_ADDED', 'TODO_CONVERTED', 'TODO_COMPLETED', 'CHECKPOINT_CREATED') NOT NULL;

-- CreateIndex
CREATE INDEX `TaskEvent_taskId_idx` ON `TaskEvent`(`taskId`);

-- CreateIndex
CREATE INDEX `TaskEvent_userId_idx` ON `TaskEvent`(`userId`);

-- AddForeignKey
ALTER TABLE `TaskEvent` ADD CONSTRAINT `TaskEvent_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
